/**
 * Microservicio orquestador
 * microservicio orquestador para conectar los microservicios de persona, oferta y negocio
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alexis.correa@accenture.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class RegistrarRequestOferta {
    id: string;
    producto: string;
    detalle: string;
    valor: string;
    descuento: string;
    tipo: string;
    foto: any;
    idnegocio: string;
    fecha_inicio: string;
    fecha_final: string;
    // ubicacion:string
        constructor(){
    
        }
}
