/**
 * Microservicio orquestador
 * microservicio orquestador para conectar los microservicios de persona, oferta y negocio
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alexis.correa@accenture.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RegistrarRequestOferta {
    id: string;
    producto: string;
    detalle: string;
    valor: string;
    descuento: string;
    foto: string;
    idnegocio: string;
    fechaInicio: string;
    fechaFinal: string;
}
