/**
 * Microservicio orquestador
 * microservicio orquestador para conectar los microservicios de persona, oferta y negocio
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alexis.correa@accenture.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class RegistrarRequestPersona {
    id: string;
    nombre: string;
    apellidos: string;
    correo: string;
    contrasena: string;
    telefono: string;
    ciudad:string;
    genero: string;
    rol: string;
    estado: string;
    token: string;
    constructor(){
        
    }
}
